const partiesData = [
    { "name": "All Ethiopian Unity Party", "type": "Country-wide", "amharic": "የመላው ኢትዮጵያ አንድነት ድርጅት", "description": "Country-wide political party" },
    { "name": "Ethiopian Democratic Union", "type": "Country-wide", "amharic": "የኢትዮጵያ ዴሞክራቲክ ኅብረት", "description": "Country-wide political party" },
    { "name": "Ethiopian National Unity Party", "type": "Country-wide", "amharic": "የኢትዮጵያ ብሔራዊ አንድነት ፓርቲ", "description": "Country-wide political party" },
    { "name": "Oromo Federalist Congress", "type": "Country-wide", "amharic": "የኦሮሞ ፌዴራላዊ ኮንግረስ", "description": "Country-wide political party (Medrek Member)" },
    { "name": "New Generation Party", "type": "Country-wide", "amharic": "አዲስ ትውልድ ፓርቲ", "description": "Country-wide political party" },
    { "name": "Ethiopian Social Democratic Party", "type": "Country-wide", "amharic": "የኢትዮጵያ ሶሻል ዲሞክራቲክ ፓርቲ", "description": "Country-wide political party (Medrek Member)" },
    { "name": "National Movement of Amhara", "type": "Country-wide", "amharic": "የአማራ ብሔራዊ ንቅናቄ", "description": "Country-wide political party" },
    { "name": "Oromo Liberation Movement", "type": "Country-wide", "amharic": "የኦሮሞ ነፃነት ንቅናቄ", "description": "Country-wide political party" },
    { "name": "Oromo Liberation Front", "type": "Country-wide", "amharic": "የኦሮሞ ነፃነት ግንባር", "description": "Country-wide political party (Alliance Member)" },
    { "name": "Ogaden National Liberation Front", "type": "Country-wide", "amharic": "የኦጋዴን ብሔራዊ ነፃነት ግንባር", "description": "Country-wide political party (Alliance Member)" },
    { "name": "Freedom and Equality Party", "type": "Country-wide", "amharic": "ነፃነትና እኩልነት ፓርቲ", "description": "Country-wide political party" },
    { "name": "Hibir Ethiopia Democratic Party", "type": "Country-wide", "amharic": "ኅብር ኢትዮጵያ ዴሞክራሲያዊ ፓርቲ", "description": "Country-wide political party" },
    { "name": "Prosperity Party", "type": "Country-wide", "amharic": "ብልፅግና ፓርቲ", "description": "Country-wide political party (Incumbent)" },
    { "name": "Ethiopian Citizens for Social Justice Party", "type": "Country-wide", "amharic": "የኢትዮጵያ ዜጎች ለማኅበራዊ-ፍትህ ፓርቲ", "description": "Country-wide political party" },
    { "name": "Ethiopian People's Revolutionary Party", "type": "Country-wide", "amharic": "የኢትዮጵያ ሕዝባዊ አብዮታዊ ፓርቲ", "description": "Country-wide political party" },
    { "name": "Enat Party", "type": "Country-wide", "amharic": "እናት ፓርቲ", "description": "Country-wide political party" },
    { "name": "Ethiopian Freedom Party", "type": "Country-wide", "amharic": "የኢትዮጵያ ነፃነት ፓርቲ", "description": "Country-wide political party" },
    { "name": "Raya Rayuma Democratic party", "type": "Country-wide", "amharic": "ራያ ራዩማ ዴሞክራሲያዊ ፓርቲ", "description": "Country-wide political party" },
    { "name": "The Ethiopian Federal Democratic Unity Forum /Medrek/", "type": "Front", "amharic": "የኢትዮጵያ ፌዴራላዊ ዴሞክራሲያዊ አንድነት መድረክ", "description": "Political Front comprising: Ethiopian Social Democratic Party, Oromo Federalist Congress, Union of Tigrians for Democracy and Sovereignty, Sidama Liberation Movement, and Afar People’s Justice Democracy Party." },
    { "name": "Alliance for Multination Democratic Federalism /Alliance/", "type": "Coalition", "amharic": "ትብብር ለሕብረ ብሔር ዲሞክራሲያዊ ፌዴራሊዝም", "description": "Political Coalition comprising: Oromo Libration Front, Ogaden National Libration Front, Mocha Democratic Party, and Agew National Congress." },

    { "name": "Union of Tigrians for Democracy and Sovereignty", "type": "Regional", "amharic": "ዓረና ትግራይ ለዲሞክራሲና ለሉዓላዊነት", "description": "Regional political party (Medrek Member)" },
    { "name": "Tigray Democratic Party", "type": "Regional", "amharic": "የትግራይ ዴሞክራሲያዊ ፓርቲ", "description": "Regional political party" },
    { "name": "Afar People's Party", "type": "Regional", "amharic": "የአፋር ሕዝብ ፓርቲ", "description": "Regional political party" },
    { "name": "Afar Revolutionary Democratic Unity Front", "type": "Regional", "amharic": "የአፋር አብዮታዊ ዴሞክራሲያዊ አንድነት ግንባር", "description": "Regional political party" },
    { "name": "Afar People Justice Democracy Party", "type": "Regional", "amharic": "የአፋር ሕዝብ ፍትሐዊ ዲሞክራሲያዊ ፓርቲ", "description": "Regional political party (Medrek Member)" },
    { "name": "Afar Liberation Front Party", "type": "Regional", "amharic": "የአፋር ነፃ አውጪ ግንባር ፓርቲ", "description": "Regional political party" },
    { "name": "Argoba People’s Democratic Organization", "type": "Regional", "amharic": "የአርጎባ ሕዝብ ዲሞክራሲያዊ ድርጅት", "description": "Regional political party" },
    { "name": "Argoba Nationality Democratic Movement", "type": "Regional", "amharic": "የአርጐባ ብሔረሰብ ዴሞክራሲያዊ ንቅናቄ", "description": "Regional political party" },
    { "name": "Kimant Democratic Party", "type": "Regional", "amharic": "ቅማንት ዴሞክራሲያዊ ፓርቲ", "description": "Regional political party" },
    { "name": "Amhara Democratic Forces Movement", "type": "Regional", "amharic": "የአማራ ዴሞክራሲያዊ ኃይል ንቅናቄ", "description": "Regional political party" },
    { "name": "Western Somali Democratic Party", "type": "Regional", "amharic": "የምዕራብ ሶማሌ ዲሞክራቲክ ፓርቲ", "description": "Regional political party" },
    { "name": "Wolene People's Democratic Party", "type": "Regional", "amharic": "የወለኔ ሕዝብ ዴሞክራሲያዊ ፓርቲ", "description": "Regional political party" },
    { "name": "Benshangul Peoples' Liberation Movement", "type": "Regional", "amharic": "የቤንሻንጉል ሕዝብ ነፃነት ንቅናቄ", "description": "Regional political party" },
    { "name": "Boro Democratic Party", "type": "Regional", "amharic": "የቦሮ ዴሞ ክራሲያዊ ፓርቲ", "description": "Regional political party" },
    { "name": "Wolaita People’s Democratic Front", "type": "Regional", "amharic": "የዎላይታ ሕዝብ ዴሞክራሲያዊ ግንባር", "description": "Regional political party" },
    { "name": "Kucha People's Democratic Party", "type": "Regional", "amharic": "የቁጫ ሕዝብ ዴሞክራሲያዊ ፓርቲ", "description": "Regional political party" },
    { "name": "Sidama Liberation Movement", "type": "Regional", "amharic": "የሲዳማ አርነት ንቅናቄ", "description": "Regional political party (Medrek Member)" },
    { "name": "Gedio People's Democratic Organization", "type": "Regional", "amharic": "የጌድዮ ሕዝብ ዴሞክራሲያዊ ድርጅት", "description": "Regional political party" },
    { "name": "Harari Democratic Organization", "type": "Regional", "amharic": "ሐረሪ ዴሞክራሲያዊ ድርጅት", "description": "Regional political party" },
    { "name": "Kafa Green Party", "type": "Regional", "amharic": "ካፋ አረንጓዴ ፓርቲ", "description": "Regional political party" },
    { "name": "Mocha Democratic Party", "type": "Regional", "amharic": "ሞቻ ዴሞክራሲያዊ ፓርቲ", "description": "Regional political party (Alliance Member)" },
    { "name": "National Movement of Wolaita", "type": "Regional", "amharic": "የዎላይታ ብሔራዊ ንቅናቄ", "description": "Regional political party" },
    { "name": "Sidama People’s Unity Democratic Organization", "type": "Regional", "amharic": "የሲዳማ ሕዝብ አንድነት ዴሞክራሲያዊ ድርጅት", "description": "Regional political party" },
    { "name": "Gamo Democratic Party", "type": "Regional", "amharic": "የጋሞ ዴሞክራሲያዊ ፓርቲ", "description": "Regional political party" },
    { "name": "Donga People's Democratic Organization", "type": "Regional", "amharic": "የዶንጋ ሕዝቦች ዴሞክራሲያዊ ድርጅት", "description": "Regional political party" },
    { "name": "Gambela Peoples' Justice for Peace and Democratic Movement", "type": "Regional", "amharic": "የጋምቤላ ሕዝቦች ፍትህ ለሰላምና ልማት ዲሞክራቲክ ንቅናቄ", "description": "Regional political party" },
    { "name": "Gambela Peoples' Liberation Movement", "type": "Regional", "amharic": "የጋምቤላ ሕዝቦች ነፃነት ንቅናቄ", "description": "Regional political party" },
    { "name": "Gambela Peoples Liberation Democratic Movement", "type": "Regional", "amharic": "የጋምቤላ ሕዝብ ነፃነት ዴሞክራሲያዊ ንቅናቄ", "description": "Regional political party" },
    { "name": "Agew National Congress", "type": "Regional", "amharic": "የአገው ብሔራዊ ሸንጎ", "description": "Regional political party (Alliance Member)" },
    { "name": "Balderas for True Democracy", "type": "Regional", "amharic": "ባልደራስ ለእውነተኛ ዲሞክራሲ", "description": "Regional political party" },
    { "name": "Sidama Unity Party", "type": "Regional", "amharic": "የሲዳማ አንድነት ፓርቲ", "description": "Regional political party" },
    { "name": "Kefa Peoples' Democratic Union", "type": "Regional", "amharic": "የካፋ ሕዝቦች ዴሞክራሲያዊ ኅብረት", "description": "Regional political party" },
    { "name": "Renaissance Party", "type": "Regional", "amharic": "ኅዳሴ ፓርቲ", "description": "Regional political party" }
];
